apiVersion: apps/v1
kind: Deployment
metadata:
  name: docketdotnet22sep2025-deployment-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docketdotnet22sep2025-dev
  template:
    metadata:
      labels:
        app: docketdotnet22sep2025-dev
    spec:
      containers:
      - name: dotnet-container
        image: ashoksarathi004/docketdotnet22sep2025:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: CUSTOM_API_KEY
          value: kubernet-dev-app

---
apiVersion: v1
kind: Service
metadata:
  name: docketdotnet22sep2025-service-dev
spec:
  selector:
    app: docketdotnet22sep2025-dev
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort